server:
  port: "8443"
  host: "0.0.0.0"
  cert_file: "/etc/orbx/certs/cert.pem"
  key_file: "/etc/orbx/certs/key.pem"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

jwt:
  secret: ""  # Set via JWT_SECRET env var

orbnet:
  endpoint: ""  # Set via ORBNET_ENDPOINT env var
  api_key: ""   # Set via ORBNET_API_KEY env var

crypto:
  quantum_safe: true
  lattice_enabled: true
  timing_enabled: true

azure:
  keyvault_url: ""  # Optional
  tenant_id: ""     # Optional
  client_id: ""     # Optional

logging:
  level: "info"
  format: "json"